// src/lib/payslipDocument.ts
// Single white/branded BULLETIN DE PAIE / PAYSLIP generator (FR + EN), styled to match
// the company template: logo top-left, company name + CNSS header, info block,
// earnings/deductions table, NET À PAYER box, signatures, footer.

import { computePayroll, deriveHourlyRate, PAYROLL_CONSTANTS } from "./payrollCalc";

export interface PayslipEmployee {
  name: string;
  matricule?: string;
  cnssNumber?: string;
  address?: string;
  qualification?: string;
  category?: string;
  echelon?: string;
  situation?: string;
  familyStatus?: string;
  numChildren?: number;
  hourlyRate?: number;
  salary?: number;       // fallback if hourlyRate not set
  position?: string;
  department?: string;
}

export interface PayslipCompany {
  companyName?: string;
  establishment?: string;
  companyCnss?: string;
  companyAddress?: string;
  monthlyHours?: number;
}

const LABELS = {
  fr: {
    title: "BULLETIN DE PAIE", month: "Mois",
    name: "Nom & Prénom", matricule: "Matricule", cnss: "N° CNSS", address: "Adresse",
    qualification: "Qualification", category: "Catégorie", echelon: "Échelon",
    situation: "Situation", family: "Sit. familiale / Nb enfants", rate: "Taux horaire",
    libelle: "Libellé", nombre: "Nombre", gains: "Gains", retenues: "Retenues",
    base: "Salaire de base", presence: "Prime de présence", transport: "Prime de transport",
    overtime: "Heures supplémentaires", absence: "Absence",
    brut: "SALAIRE BRUT", cnssEmp: "CNSS", cnssInfo: "CNSS globale — information", imposable: "Salaire imposable", irpp: "Impôt sur salaire",
    css: "Contribution sociale de solidarité", avance: "Avance sur salaire", net: "SALAIRE NET",
    netToPay: "NET À PAYER", emarg: "Émargement employé", employer: "L'employeur",
    footer: "Document généré par EMM+ — Service Paie",
  },
  en: {
    title: "PAYSLIP", month: "Month",
    name: "Full Name", matricule: "ID No.", cnss: "CNSS No.", address: "Address",
    qualification: "Qualification", category: "Category", echelon: "Step",
    situation: "Status", family: "Marital status / Children", rate: "Hourly rate",
    libelle: "Description", nombre: "Number", gains: "Earnings", retenues: "Deductions",
    base: "Base salary", presence: "Attendance bonus", transport: "Transport allowance",
    overtime: "Overtime", absence: "Absence",
    brut: "GROSS SALARY", cnssEmp: "CNSS", cnssInfo: "Total CNSS — info", imposable: "Taxable salary", irpp: "Income tax",
    css: "Social solidarity contribution", avance: "Salary advance", net: "NET SALARY",
    netToPay: "NET PAYABLE", emarg: "Employee signature", employer: "Employer",
    footer: "Document generated by EMM+ — Payroll Service",
  },
};

// Stack-safe base64 of /logo.png (returns null if missing)
async function loadLogo(): Promise<string | null> {
  try {
    const res = await fetch("/logo.png");
    if (!res.ok) return null;
    const buf = await res.arrayBuffer();
    const bytes = new Uint8Array(buf);
    let bin = "";
    for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
    return btoa(bin);
  } catch {
    return null;
  }
}

// Tunisian style: dot decimal, space thousands  → 81 000.000
function fmt(n: number): string {
  const [int, dec] = Math.abs(n).toFixed(3).split(".");
  const grouped = int.replace(/\B(?=(\d{3})+(?!\d))/g, " ");
  return (n < 0 ? "-" : "") + grouped + "." + dec;
}

export async function generatePayslip(opts: {
  employee: PayslipEmployee;
  company: PayslipCompany;
  period: string;            // "2026-02"
  avancesTotal?: number;
  absenceHours?: number;
  overtimeHours?: number;
  language?: "fr" | "en";
}): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const lang = opts.language === "en" ? "en" : "fr";
  const L = LABELS[lang];
  const emp = opts.employee;
  const co = opts.company || {};
  // Taux horaire is always derived from the standard 208h rate: salary / (26 × 8)
  const hourlyRate = deriveHourlyRate(emp.salary || 0, PAYROLL_CONSTANTS.monthlyHours);

  // Actual hours worked — passed from the payroll page via company.monthlyHours
  // Falls back to 208 only if not provided (full month assumption)
  const actualHours = co.monthlyHours ?? PAYROLL_CONSTANTS.monthlyHours;

  const p = computePayroll({
    salary: emp.salary,
    hourlyRate,
    monthlyHours: actualHours,
    familyStatus: emp.familyStatus,
    numChildren: emp.numChildren,
    avancesTotal: opts.avancesTotal || 0,
    absenceHours: opts.absenceHours || 0,
    overtimeHours: opts.overtimeHours || 0,
  });

  const [yy, mm] = opts.period.split("-").map(Number);
  const monthName = new Date(yy, (mm || 1) - 1).toLocaleDateString(lang === "fr" ? "fr-FR" : "en-US", {
    month: "long",
    year: "numeric",
  });

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 14;
  const NAVY: [number, number, number] = [27, 42, 107];
  const INK: [number, number, number] = [20, 20, 20];
  const GRAYTXT: [number, number, number] = [90, 90, 90];

  // ── Header: logo + company name/establishment + company CNSS ──
  const logo = await loadLogo();
  let logoW = 0;
  if (logo) {
    // Preserve the logo's real aspect ratio — fit inside a 30×22mm box, never squished
    const maxW = 30, maxH = 22;
    let w = maxW, h = maxH;
    try {
      const props = doc.getImageProperties(logo);
      const ratio = (props.width || 1) / (props.height || 1);
      w = maxW; h = w / ratio;
      if (h > maxH) { h = maxH; w = h * ratio; }
    } catch { w = maxW; h = maxW * 0.66; }
    doc.addImage(logo, "PNG", M, 12, w, h);
    logoW = w;
  }
  const textX = logo ? M + logoW + 5 : M;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...NAVY);
  doc.text(co.companyName || "EMM Hardware", textX, 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAYTXT);
  doc.text(co.establishment || "Établissement Mohamed Moalla Plus", textX, 26);
  if (co.companyAddress) doc.text(co.companyAddress, textX, 31);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.text("CNSS N°", W - M, 17, { align: "right" });
  doc.text(co.companyCnss || "—", W - M, 24, { align: "right" });

  doc.setDrawColor(...INK);
  doc.setLineWidth(0.6);
  doc.line(M, 40, W - M, 40);

  // ── Title + period ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...INK);
  doc.text(L.title, W / 2, 50, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`${L.month} : ${monthName}`, W / 2, 57, { align: "center" });

  // ── Employee info block ──
  const familyVal = `${emp.familyStatus || ""}${emp.numChildren ? " / " + emp.numChildren : ""}`.trim();
  const infoRows: string[][] = [
    [L.name, emp.name || ""],
    [L.matricule, emp.matricule || ""],
    [L.cnss, emp.cnssNumber || ""],
    [L.address, emp.address || ""],
    [L.qualification, emp.qualification || ""],
    [L.category, emp.category || ""],
    [L.echelon, emp.echelon || ""],
    [L.situation, emp.situation || ""],
    [L.family, familyVal],
    [L.rate, hourlyRate ? fmt(hourlyRate) : ""],
  ];

  autoTable(doc, {
    startY: 64,
    body: infoRows,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 9, cellPadding: 2.1, lineColor: [120, 120, 120], lineWidth: 0.1, textColor: INK },
    columnStyles: {
      0: { cellWidth: 58, fontStyle: "bold", fillColor: [240, 240, 240] },
      1: { cellWidth: W - 2 * M - 58 },
    },
    margin: { left: M, right: M },
  });

  // ── Earnings / deductions table ──
  const afterInfo = (doc as any).lastAutoTable.finalY + 6;
  const GRAY: [number, number, number] = [120, 120, 120];
  const body: any[] = [
    [L.base, fmt(PAYROLL_CONSTANTS.monthlyHours), fmt(p.agreedSalary), ""],
    [
      { content: L.brut, styles: { fontStyle: "bold" } }, fmt(p.hours),
      { content: fmt(p.brut), styles: { fontStyle: "bold" } }, "",
    ],
    [L.cnssEmp, "", "", fmt(p.cnssEmployee)],
    [L.imposable, "", fmt(p.imposable), ""],
    [L.irpp, "", "", fmt(p.irpp)],
    [L.css, "", "", fmt(p.css)],
    [
      { content: L.net, styles: { fontStyle: "bold" } }, "",
      { content: fmt(p.net), styles: { fontStyle: "bold" } }, "",
    ],
  ];
  if (p.overtimePay > 0) body.push([L.overtime, fmt(p.overtimeHours), fmt(p.overtimePay), ""]);
  if (p.absenceDeduction > 0) body.push([L.absence, fmt(p.absenceHours), "", fmt(p.absenceDeduction)]);
  if (p.avances > 0) body.push([L.avance, "", "", fmt(p.avances)]);
  // 29.67% total CNSS — information only (amount in the "Nombre" column, never a deduction)
  body.push([
    { content: L.cnssInfo, styles: { fontStyle: "italic", textColor: GRAY } },
    { content: fmt(p.cnssTotal), styles: { textColor: GRAY } },
    "", "",
  ]);

  autoTable(doc, {
    startY: afterInfo,
    head: [[L.libelle, L.nombre, L.gains, L.retenues]],
    body,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 9, cellPadding: 2.4, lineColor: [120, 120, 120], lineWidth: 0.1, textColor: INK },
    headStyles: { fillColor: [225, 225, 225], textColor: INK, fontStyle: "bold", halign: "left", fontSize: 8.5 },
    columnStyles: {
      0: { cellWidth: (W - 2 * M) * 0.46 },
      1: { halign: "right", cellWidth: (W - 2 * M) * 0.16 },
      2: { halign: "right", cellWidth: (W - 2 * M) * 0.19 },
      3: { halign: "right", cellWidth: (W - 2 * M) * 0.19 },
    },
    margin: { left: M, right: M },
  });

  // ── NET À PAYER box (bottom-right) ──
  const afterTable = (doc as any).lastAutoTable.finalY + 10;
  const boxW = 78, boxH = 17, boxX = W - M - boxW, boxY = afterTable;
  doc.setDrawColor(...INK);
  doc.setLineWidth(0.5);
  doc.rect(boxX, boxY, boxW, boxH);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text(L.netToPay, boxX + boxW / 2, boxY + 6.5, { align: "center" });
  doc.setFontSize(13);
  doc.text(`${fmt(p.netToPay)} DT`, boxX + boxW / 2, boxY + 13.5, { align: "center" });

  // ── Signatures ──
  const sigY = boxY + boxH + 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAYTXT);
  doc.text(L.emarg, M, sigY);
  doc.text(L.employer, W - M, sigY, { align: "right" });
  doc.setDrawColor(150, 150, 150);
  doc.setLineWidth(0.2);
  doc.line(M, sigY + 13, M + 62, sigY + 13);
  doc.line(W - M - 62, sigY + 13, W - M, sigY + 13);

  // ── Footer ──
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(140, 140, 140);
  doc.text(L.footer, W / 2, 286, { align: "center" });

  const safeName = (emp.name || "employee").replace(/\s+/g, "_");
  doc.save(`Bulletin_${safeName}_${opts.period}.pdf`);
}