"use client";

import ProtectedRoute from "@/components/ProtectedRoute";
import { financeService, FinanceReportsResponse, DepartmentExpensesResponse, TvaDeclarationResponse, SalesReportResponse } from "@/services/finance/financeService";
import { useLanguage } from "@/context/LanguageContext";
import { useEffect, useState } from "react";
import { BarChart3, FileText, Loader2, Printer, ShoppingCart, TrendingUp, Users } from "lucide-react";

function getErrorMessage(err: unknown) {
  if (
    typeof err === "object" &&
    err !== null &&
    "response" in err &&
    typeof err.response === "object" &&
    err.response !== null &&
    "data" in err.response &&
    typeof err.response.data === "object" &&
    err.response.data !== null &&
    "message" in err.response.data &&
    typeof err.response.data.message === "string"
  ) {
    return err.response.data.message;
  }
  return "Échec du chargement des rapports";
}

function tnd(value: number | undefined | null) {
  return `${(value ?? 0).toLocaleString("fr-TN", { minimumFractionDigits: 3 })} TND`;
}

function Row({ label, value, bold }: { label: string; value: number | undefined | null; bold?: boolean }) {
  return (
    <div className={`flex justify-between ${bold ? "border-t border-slate-100 pt-2 dark:border-slate-800" : ""}`}>
      <span className={bold ? "font-semibold text-slate-900 dark:text-white" : ""}>{label}</span>
      <span className={bold ? "font-semibold text-slate-900 dark:text-white" : ""}>{tnd(value)}</span>
    </div>
  );
}

const card = "rounded-2xl border border-slate-100 p-5 dark:border-slate-800";
const surface = "rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900";
const inputClass = "rounded-2xl border border-slate-200 bg-white px-4 py-2.5 text-sm text-slate-900 outline-none transition focus:border-slate-400 dark:border-slate-700 dark:bg-slate-950 dark:text-white";

const MONTHS_FR = [
  "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
  "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre",
];

function TvaRow({ label, value, bold, negative }: { label: string; value: number | undefined | null; bold?: boolean; negative?: boolean }) {
  return (
    <div className={`flex justify-between py-2 ${bold ? "border-t border-slate-200 font-semibold text-slate-900 dark:border-slate-700 dark:text-white" : "text-slate-600 dark:text-slate-300"}`}>
      <span>{label}</span>
      <span className={negative ? "text-rose-600 dark:text-rose-400" : ""}>{tnd(value)}</span>
    </div>
  );
}

function printTvaDeclaration(data: TvaDeclarationResponse, monthName: string, autoGeneratedNote: string) {
  const html = `<!doctype html>
<html>
  <head><meta charset="utf-8"/><title>Déclaration TVA · ${monthName} ${data.period.year}</title></head>
  <body style="font-family:Arial,sans-serif;color:#0f172a;padding:32px;max-width:600px;margin:auto">
    <div style="border-bottom:2px solid #0f172a;padding-bottom:12px;margin-bottom:24px;display:flex;justify-content:space-between">
      <div>
        <div style="font-size:16px;font-weight:700">Déclaration TVA mensuelle</div>
        <div style="font-size:12px;color:#64748b;margin-top:4px">Période : ${monthName} ${data.period.year}</div>
      </div>
      <div style="font-size:11px;color:#64748b;text-align:right">Généré le ${new Date().toLocaleDateString("fr-TN")}</div>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead>
        <tr style="background:#f8fafc">
          <th style="text-align:left;padding:8px 12px;border:1px solid #e2e8f0">Désignation</th>
          <th style="text-align:right;padding:8px 12px;border:1px solid #e2e8f0">Montant (TND)</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0;color:#64748b">Base HT ventes</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.salesRevenue.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0;color:#64748b">Base HT achats</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.purchasesHt.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0">4457 — TVA collectée (ventes)</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.tvaCollectee.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0">4456 — TVA déductible (achats)</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">(${data.tvaDeductible.toFixed(3)})</td></tr>
        <tr style="font-weight:700;background:#f8fafc"><td style="padding:8px 12px;border:1px solid #e2e8f0">TVA nette à verser</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right;color:${data.tvaNet >= 0 ? "#0f172a" : "#16a34a"}">${data.tvaNet.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0">44581 — FODEC collecté</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.fodecCollecte.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0">4371 — Timbre fiscal à décaisser</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.timbreADecaisser.toFixed(3)}</td></tr>
        <tr><td style="padding:8px 12px;border:1px solid #e2e8f0">4028 — Retenues à la source à décaisser</td><td style="padding:8px 12px;border:1px solid #e2e8f0;text-align:right">${data.rsADecaisser.toFixed(3)}</td></tr>
      </tbody>
    </table>
    <div style="margin-top:32px;font-size:10px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px">
      ${autoGeneratedNote}
    </div>
  </body>
</html>`;
  const win = window.open("", "_blank", "width=700,height=600");
  if (win) { win.document.open(); win.document.write(html); win.document.close(); setTimeout(() => win.print(), 300); }
}

export default function FinanceReportsPage() {
  const { t } = useLanguage();

  const [reports, setReports] = useState<FinanceReportsResponse | null>(null);
  const [deptExpenses, setDeptExpenses] = useState<DepartmentExpensesResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const now = new Date();
  const [tvaYear, setTvaYear] = useState(now.getFullYear());
  const [tvaMonth, setTvaMonth] = useState(now.getMonth() + 1);
  const [tvaData, setTvaData] = useState<TvaDeclarationResponse | null>(null);
  const [tvaLoading, setTvaLoading] = useState(false);
  const [tvaError, setTvaError] = useState("");
  const tvaYears = Array.from({ length: 5 }, (_, i) => now.getFullYear() - i);

  const defaultFrom = `${now.getFullYear()}-01-01`;
  const defaultTo = now.toISOString().slice(0, 10);
  const [salesFrom, setSalesFrom] = useState(defaultFrom);
  const [salesTo, setSalesTo] = useState(defaultTo);
  const [salesData, setSalesData] = useState<SalesReportResponse | null>(null);
  const [salesLoading, setSalesLoading] = useState(false);
  const [salesError, setSalesError] = useState("");

  const loadSales = async () => {
    try {
      setSalesLoading(true);
      setSalesError("");
      setSalesData(await financeService.getSalesReport(salesFrom, salesTo));
    } catch (err: unknown) {
      setSalesError(
        typeof err === "object" && err !== null && "response" in err
          ? ((err as { response?: { data?: { message?: string } } }).response?.data?.message || t("fin_failed"))
          : t("fin_failed")
      );
    } finally {
      setSalesLoading(false);
    }
  };

  const loadTva = async () => {
    try {
      setTvaLoading(true);
      setTvaError("");
      setTvaData(await financeService.getTvaDeclaration(tvaYear, tvaMonth));
    } catch (err: unknown) {
      setTvaError(
        typeof err === "object" && err !== null && "response" in err
          ? ((err as { response?: { data?: { message?: string } } }).response?.data?.message || t("fin_failed"))
          : t("fin_failed")
      );
    } finally {
      setTvaLoading(false);
    }
  };

  useEffect(() => {
    const run = async () => {
      try {
        setLoading(true);
        setError("");
        const [r, d] = await Promise.all([
          financeService.getReports(),
          financeService.getDepartmentExpenses(),
        ]);
        setReports(r);
        setDeptExpenses(d);
      } catch (err) {
        setError(getErrorMessage(err));
      } finally {
        setLoading(false);
      }
    };
    run();
  }, []);

  return (
    <ProtectedRoute allowedRoles={["ADMIN", "FINANCE_MANAGER"]}>
      <div className="space-y-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 dark:bg-slate-800">
            <BarChart3 size={18} className="text-slate-600 dark:text-slate-300" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white">
              {t("fin_reportsTitle")}
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400">
              {t("fin_reportsSubtitle")}
            </p>
          </div>
        </div>

        {error ? (
          <div className="rounded-3xl border border-rose-200 bg-rose-50 px-6 py-4 text-sm text-rose-600 dark:border-rose-900/40 dark:bg-rose-950/20 dark:text-rose-400">
            {error}
          </div>
        ) : null}

        {loading || !reports ? (
          <div className="flex items-center justify-center gap-2 rounded-3xl border border-slate-200 bg-white py-16 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400">
            <Loader2 size={16} className="animate-spin" />
            {t("fin_loadingReports")}
          </div>
        ) : (
          <div className="space-y-6">
            {/* Balance sheet */}
            <div className={surface}>
              <h2 className="mb-5 font-semibold text-slate-950 dark:text-white">{t("fin_balanceSheet")}</h2>
              <div className="grid gap-4 md:grid-cols-2">
                <div className={card}>
                  <h3 className="mb-4 text-sm font-medium text-slate-900 dark:text-white">{t("fin_assets")}</h3>
                  <div className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
                    <Row label="411 — Créances clients" value={reports.balanceSheet.assets.receivables} />
                    <Row label="531 — Caisse" value={reports.balanceSheet.assets.cash} />
                    <Row label="512 — Banque" value={reports.balanceSheet.assets.bank} />
                    <Row label={t("fin_totalAssets")} value={reports.balanceSheet.assets.total} bold />
                  </div>
                </div>
                <div className={card}>
                  <h3 className="mb-4 text-sm font-medium text-slate-900 dark:text-white">{t("fin_liabilities")}</h3>
                  <div className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
                    <Row label="401 — Dettes fournisseurs" value={reports.balanceSheet.liabilities.supplierPayables} />
                    <Row label="4457 — TVA collectée" value={reports.balanceSheet.liabilities.tvaCollectee} />
                    <Row label="44581 — FODEC collecté" value={reports.balanceSheet.liabilities.fodecCollecte} />
                    <Row label="4371 — Timbre fiscal à décaisser" value={reports.balanceSheet.liabilities.timbreADecaisser} />
                    <Row label="4028 — Retenues à la source à décaisser" value={reports.balanceSheet.liabilities.rsADecaisser} />
                    <Row label={t("fin_totalLiabilities")} value={reports.balanceSheet.liabilities.total} bold />
                  </div>
                </div>
              </div>
            </div>

            {/* P&L */}
            <div className={surface}>
              <h2 className="mb-5 font-semibold text-slate-950 dark:text-white">{t("fin_pnl")}</h2>
              <div className="grid gap-4 md:grid-cols-2">
                <div className={card}>
                  <h3 className="mb-4 text-sm font-medium text-slate-900 dark:text-white">{t("fin_products")}</h3>
                  <div className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
                    <Row label="706 — Ventes de marchandises" value={reports.profitAndLoss.revenue.salesRevenue} />
                    <Row label="609 — Avoirs fournisseurs" value={reports.profitAndLoss.revenue.purchaseCredits} />
                    <Row label={t("fin_totalProducts")} value={reports.profitAndLoss.revenue.total} bold />
                  </div>
                </div>
                <div className={card}>
                  <h3 className="mb-4 text-sm font-medium text-slate-900 dark:text-white">{t("fin_expenses")}</h3>
                  <div className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
                    <Row label="607 — Achats de marchandises" value={reports.profitAndLoss.expenses.purchasesExpense} />
                    <Row label="60800 — FODEC sur achats" value={reports.profitAndLoss.expenses.fodecAchats} />
                    <Row label="6371 — Timbre fiscal" value={reports.profitAndLoss.expenses.timbreFiscal} />
                    <Row label={t("fin_totalExpenses")} value={reports.profitAndLoss.expenses.total} bold />
                  </div>
                </div>
              </div>

              <div className={`${card} mt-4`}>
                <h3 className="mb-4 text-sm font-medium text-slate-900 dark:text-white">{t("fin_taxPosition")}</h3>
                <div className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
                  <Row label="4457 — TVA collectée (ventes)" value={reports.profitAndLoss.tax.tvaCollectee} />
                  <Row label="4456 — TVA déductible (achats)" value={reports.profitAndLoss.tax.tvaDeductible} />
                  <Row label={t("fin_tvaNet")} value={reports.profitAndLoss.tax.tvaNet} bold />
                  <div className="pt-2" />
                  <Row label="44581 — FODEC collecté (ventes)" value={reports.profitAndLoss.tax.fodecCollecte} />
                  <Row label="4371 — Timbre à décaisser" value={reports.profitAndLoss.tax.timbreADecaisser} />
                  <Row label="4028 — RS à décaisser" value={reports.profitAndLoss.tax.rsADecaisser} />
                </div>
              </div>

              <div className="mt-4 rounded-2xl bg-slate-900 px-5 py-4 text-sm font-semibold text-white dark:bg-slate-950">
                {t("fin_netResult")} {tnd(reports.profitAndLoss.netResult)}
              </div>
            </div>

            {/* Department expenses */}
            {deptExpenses && (
              <div className={surface}>
                <div className="mb-5 flex items-center gap-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-violet-100 dark:bg-violet-950/40">
                    <Users size={15} className="text-violet-600 dark:text-violet-400" />
                  </div>
                  <div>
                    <h2 className="font-semibold text-slate-950 dark:text-white">{t("fin_deptExpenses")}</h2>
                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      {t("fin_monthlySalary")} · {deptExpenses.totalEmployees} {deptExpenses.totalEmployees !== 1 ? t("fin_employees") : t("fin_employee")} {t("fin_active")}
                    </p>
                  </div>
                  <div className="ml-auto text-right">
                    <p className="text-xs text-slate-400">{t("fin_totalSalary")}</p>
                    <p className="text-lg font-bold text-slate-950 dark:text-white">{tnd(deptExpenses.totalSalary)}</p>
                  </div>
                </div>

                {deptExpenses.departments.length === 0 ? (
                  <p className="py-6 text-center text-sm text-slate-400">{t("fin_noEmployees")}</p>
                ) : (
                  <div className="space-y-3">
                    {deptExpenses.departments.map((dept) => {
                      const pct = deptExpenses.totalSalary > 0
                        ? Math.round((dept.totalSalary / deptExpenses.totalSalary) * 100)
                        : 0;
                      return (
                        <div key={dept.department} className={card}>
                          <div className="mb-2 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                              <span className="font-medium text-slate-900 dark:text-white">{dept.department}</span>
                              <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] font-medium text-slate-500 dark:bg-slate-800 dark:text-slate-400">
                                {dept.employeeCount} pers.
                              </span>
                              {dept.onLeaveCount > 0 && (
                                <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-600 dark:bg-amber-950/30 dark:text-amber-400">
                                  {dept.onLeaveCount} {t("fin_onLeave")}
                                </span>
                              )}
                            </div>
                            <div className="text-right">
                              <span className="text-sm font-semibold text-slate-900 dark:text-white">{tnd(dept.totalSalary)}</span>
                              <span className="ml-2 text-xs text-slate-400">{pct}%</span>
                            </div>
                          </div>
                          <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                            <div
                              className="h-full rounded-full bg-violet-500 dark:bg-violet-600 transition-all"
                              style={{ width: `${pct}%` }}
                            />
                          </div>
                          <div className="mt-1.5 text-xs text-slate-400">
                            {t("fin_avgSalary")} {tnd(dept.avgSalary)}
                          </div>
                        </div>
                      );
                    })}

                    <div className="flex items-center justify-between rounded-2xl bg-slate-900 px-5 py-3.5 text-sm font-semibold text-white dark:bg-slate-950">
                      <span>{t("fin_totalMonthlySalary")}</span>
                      <span>{tnd(deptExpenses.totalSalary)}</span>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Sales Report */}
            <div className={surface}>
              <div className="mb-5 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-100 dark:bg-emerald-950/40">
                  <ShoppingCart size={15} className="text-emerald-600 dark:text-emerald-400" />
                </div>
                <div>
                  <h2 className="font-semibold text-slate-950 dark:text-white">{t("fin_salesReport")}</h2>
                  <p className="text-xs text-slate-500 dark:text-slate-400">
                    {t("fin_salesSubtitle")}
                  </p>
                </div>
              </div>

              <div className="flex flex-wrap items-end gap-4">
                <label className="block text-sm">
                  <span className="mb-1.5 block text-slate-600 dark:text-slate-300">{t("fin_from")}</span>
                  <input type="date" className={inputClass} value={salesFrom} onChange={(e) => setSalesFrom(e.target.value)} />
                </label>
                <label className="block text-sm">
                  <span className="mb-1.5 block text-slate-600 dark:text-slate-300">{t("fin_to")}</span>
                  <input type="date" className={inputClass} value={salesTo} onChange={(e) => setSalesTo(e.target.value)} />
                </label>
                <button
                  onClick={loadSales}
                  disabled={salesLoading}
                  className="inline-flex items-center gap-2 rounded-2xl border border-black bg-black px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-slate-900 disabled:opacity-60"
                >
                  {salesLoading ? <Loader2 size={15} className="animate-spin" /> : null}
                  {t("fin_calculate")}
                </button>
              </div>

              {salesError ? (
                <div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-600 dark:border-rose-900/40 dark:bg-rose-950/20 dark:text-rose-400">
                  {salesError}
                </div>
              ) : null}

              {salesData ? (
                <div className="mt-5 space-y-5">
                  <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
                    <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/40">
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{t("fin_invoicesCount")}</p>
                      <p className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{salesData.summary.totalCount}</p>
                    </div>
                    <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/40">
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">{t("fin_totalHt")}</p>
                      <p className="mt-1 text-lg font-bold text-slate-900 dark:text-white">{tnd(salesData.summary.totalHt)}</p>
                    </div>
                    <div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 dark:border-emerald-900/30 dark:bg-emerald-950/20">
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">{t("fin_totalCollected")}</p>
                      <p className="mt-1 text-lg font-bold text-emerald-700 dark:text-emerald-400">{tnd(salesData.summary.totalPaid)}</p>
                      <p className="text-xs text-emerald-600/70 dark:text-emerald-500">{salesData.summary.paidCount} {t("fin_invoicesCount").toLowerCase()}</p>
                    </div>
                    <div className="rounded-2xl border border-rose-100 bg-rose-50 p-4 dark:border-rose-900/30 dark:bg-rose-950/20">
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-rose-600 dark:text-rose-400">{t("fin_totalUnpaid")}</p>
                      <p className="mt-1 text-lg font-bold text-rose-700 dark:text-rose-400">{tnd(salesData.summary.totalUnpaid)}</p>
                      <p className="text-xs text-rose-600/70 dark:text-rose-500">{salesData.summary.unpaidCount} {t("fin_invoicesCount").toLowerCase()}</p>
                    </div>
                  </div>

                  <div className="flex items-center justify-between rounded-2xl bg-slate-900 px-5 py-4 text-sm font-semibold text-white dark:bg-slate-950">
                    <span className="flex items-center gap-2"><TrendingUp size={15} /> {t("fin_totalRevenueTtc")}</span>
                    <span>{tnd(salesData.summary.totalTtc)}</span>
                  </div>

                  {salesData.byMonth.length > 0 && (
                    <div>
                      <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">{t("fin_monthlyEvolution")}</p>
                      <div className="overflow-hidden rounded-2xl border border-slate-100 dark:border-slate-800">
                        <table className="w-full text-sm">
                          <thead className="bg-slate-50 dark:bg-slate-950/50">
                            <tr>
                              {[t("fin_month"), t("fin_invoicesCount"), t("fin_totalHt"), "Total TTC"].map((h) => (
                                <th key={h} className="px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-wider text-slate-400">{h}</th>
                              ))}
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                            {salesData.byMonth.map((row) => {
                              const [y, m] = row.month.split("-");
                              const label = `${MONTHS_FR[parseInt(m) - 1]} ${y}`;
                              return (
                                <tr key={row.month} className="text-slate-700 dark:text-slate-300">
                                  <td className="px-4 py-3 font-medium text-slate-900 dark:text-white">{label}</td>
                                  <td className="px-4 py-3">{row.count}</td>
                                  <td className="px-4 py-3">{tnd(row.totalHt)}</td>
                                  <td className="px-4 py-3 font-semibold">{tnd(row.totalTtc)}</td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  )}

                  {salesData.topCustomers.length > 0 && (
                    <div>
                      <p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">{t("fin_topClients")}</p>
                      <div className="space-y-2">
                        {salesData.topCustomers.map((c, i) => {
                          const pct = salesData.summary.totalTtc > 0
                            ? Math.round((c.totalTtc / salesData.summary.totalTtc) * 100)
                            : 0;
                          return (
                            <div key={c.customerName} className="flex items-center gap-3">
                              <span className="w-5 text-right text-xs font-semibold text-slate-400">{i + 1}</span>
                              <div className="flex-1">
                                <div className="mb-1 flex items-center justify-between text-sm">
                                  <span className="font-medium text-slate-900 dark:text-white">{c.customerName}</span>
                                  <span className="text-slate-500 dark:text-slate-400">{tnd(c.totalTtc)} <span className="text-xs text-slate-400">({pct}%)</span></span>
                                </div>
                                <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800">
                                  <div className="h-full rounded-full bg-emerald-500 dark:bg-emerald-600" style={{ width: `${pct}%` }} />
                                </div>
                              </div>
                              <span className="w-8 text-right text-xs text-slate-400">{c.count}×</span>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              ) : null}
            </div>

            {/* TVA Report */}
            <div className={surface}>
              <div className="mb-5 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-sky-100 dark:bg-sky-950/40">
                  <FileText size={15} className="text-sky-600 dark:text-sky-400" />
                </div>
                <div>
                  <h2 className="font-semibold text-slate-950 dark:text-white">{t("fin_tvaReport")}</h2>
                  <p className="text-xs text-slate-500 dark:text-slate-400">
                    {t("fin_tvaSubtitle")}
                  </p>
                </div>
              </div>

              <div className="flex flex-wrap items-end gap-4">
                <label className="block text-sm">
                  <span className="mb-1.5 block text-slate-600 dark:text-slate-300">{t("fin_year")}</span>
                  <select className={inputClass} value={tvaYear} onChange={(e) => setTvaYear(Number(e.target.value))}>
                    {tvaYears.map((y) => <option key={y} value={y}>{y}</option>)}
                  </select>
                </label>
                <label className="block text-sm">
                  <span className="mb-1.5 block text-slate-600 dark:text-slate-300">{t("fin_month")}</span>
                  <select className={inputClass} value={tvaMonth} onChange={(e) => setTvaMonth(Number(e.target.value))}>
                    {MONTHS_FR.map((m, i) => <option key={i + 1} value={i + 1}>{m}</option>)}
                  </select>
                </label>
                <button
                  onClick={loadTva}
                  disabled={tvaLoading}
                  className="inline-flex items-center gap-2 rounded-2xl border border-black bg-black px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-slate-900 disabled:opacity-60"
                >
                  {tvaLoading ? <Loader2 size={15} className="animate-spin" /> : null}
                  {t("fin_calculate")}
                </button>
              </div>

              {tvaError ? (
                <div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-600 dark:border-rose-900/40 dark:bg-rose-950/20 dark:text-rose-400">
                  {tvaError}
                </div>
              ) : null}

              {tvaData ? (
                <div className="mt-5">
                  <div className="mb-4 flex items-center justify-between">
                    <p className="text-sm font-medium text-slate-700 dark:text-slate-300">
                      {t("fin_declaration")} — {MONTHS_FR[tvaData.period.month - 1]} {tvaData.period.year}
                    </p>
                    <button
                      onClick={() => printTvaDeclaration(tvaData, MONTHS_FR[tvaData.period.month - 1], t("fin_autoGenerated"))}
                      className="inline-flex items-center gap-2 rounded-2xl border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"
                    >
                      <Printer size={14} />
                      {t("fin_print")}
                    </button>
                  </div>

                  <div className="divide-y divide-slate-100 text-sm dark:divide-slate-800">
                    <div className="pb-3">
                      <p className="mb-2 text-xs font-medium uppercase tracking-wider text-slate-400">{t("fin_taxBase")}</p>
                      <TvaRow label={t("fin_revenueHt")} value={tvaData.salesRevenue} />
                      <TvaRow label={t("fin_purchasesHt")} value={tvaData.purchasesHt} />
                    </div>
                    <div className="py-3">
                      <p className="mb-2 mt-1 text-xs font-medium uppercase tracking-wider text-slate-400">{t("fin_tvaTax")}</p>
                      <TvaRow label={t("fin_tvaCollected")} value={tvaData.tvaCollectee} />
                      <TvaRow label={t("fin_tvaDeductible")} value={tvaData.tvaDeductible} />
                      <TvaRow label={t("fin_tvaNet")} value={tvaData.tvaNet} bold negative={tvaData.tvaNet < 0} />
                    </div>
                    <div className="py-3">
                      <p className="mb-2 mt-1 text-xs font-medium uppercase tracking-wider text-slate-400">{t("fin_parafiscal")}</p>
                      <TvaRow label={t("fin_fodec")} value={tvaData.fodecCollecte} />
                      <TvaRow label={t("fin_timbre")} value={tvaData.timbreADecaisser} />
                    </div>
                    <div className="pt-3">
                      <p className="mb-2 mt-1 text-xs font-medium uppercase tracking-wider text-slate-400">{t("fin_rsLabel")}</p>
                      <TvaRow label="RS à décaisser (4028)" value={tvaData.rsADecaisser} />
                    </div>
                  </div>

                  <div className="mt-5 rounded-2xl bg-slate-900 px-5 py-4 text-sm font-semibold text-white dark:bg-slate-950">
                    <div className="flex justify-between">
                      <span>{t("fin_toDGI")}</span>
                      <span>{tnd((tvaData.tvaNet > 0 ? tvaData.tvaNet : 0) + tvaData.fodecCollecte + tvaData.timbreADecaisser + tvaData.rsADecaisser)}</span>
                    </div>
                  </div>

                  <p className="mt-3 text-xs text-slate-400 dark:text-slate-500">
                    {t("fin_autoGenerated")}
                  </p>
                </div>
              ) : null}
            </div>

          </div>
        )}
      </div>
    </ProtectedRoute>
  );
}
